name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
  
  publish:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    steps:
    - uses: actions/checkout@v2
    - name: Run install
      run: cargo install --force wasm-pack
    - name: Run build
      run: |
        wasm-pack build --target web --out-name wasm --out-dir ./public
        cp static/* public/
        git add --force public
    - uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./
